# Generated by Django 3.2.3 on 2021-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE_UG', 'Computer Science and Engineering (Undergraduate)'), ('ECE_UG', 'Electronics and Communications Engineering (Undergraduate)')], default='CSE_UG', max_length=100, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('IIITRANCHI', 'Indian Institute of Information Technology Ranchi'), ('INSTI_A', 'Institute A'), ('INSTI_B', 'Institute B'), ('INSTI_C', 'Institute C'), ('INSTI_D', 'Institute D'), ('OTHER', 'Other Institute')], default='IIITRANCHI', max_length=100, verbose_name='institute name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_language',
            field=models.CharField(blank=True, choices=[('PY', 'Python'), ('CPP', 'C++'), ('C', 'C'), ('JAVA', 'Java')], default='PY', max_length=5, verbose_name='primary programming language'),
        ),
    ]
